export const DIMENSIONS = { width: 180, height: 135 };

/**
 * Example circuit used to make the tour
 */
export default {
  id: 'tour-circuit',
  name: "Logossim's tour circuit",
  createdAt: '2020-05-21T20:18:00.000Z',
  updatedAt: '2020-09-08T11:47:00.000Z',
  circuit: {
    id: 'tour-circuit',
    locked: false,
    offsetX: 0,
    offsetY: 0,
    zoom: 100,
    gridSize: 15,
    layers: [
      {
        id: '4d94cbed-1005-4dc6-b0e3-44d71dc14380',
        type: 'diagram-links',
        isSvg: true,
        transformed: true,
        models: {
          'clock-out-link': {
            id: 'clock-out-link',
            type: 'link',
            selected: false,
            source: 'clock',
            sourcePort: 'clock-port',
            target: 'and',
            targetPort: 'and-port-in0',
            points: [
              {
                id: 'bb7c0935-a272-45ea-b47a-f9b79fa7fac3',
                type: 'point',
                x: 30,
                y: 15,
              },
              {
                id: '2f339615-1c6c-450c-9862-06742ed3893f',
                type: 'point',
                x: 60,
                y: 15,
              },
            ],
            labels: [],
            bifurcations: [],
            bifurcationSource: null,
            bifurcationTarget: null,
            value: null,
            bits: 1,
          },
          'and-out-link': {
            id: 'and-out-link',
            type: 'link',
            selected: false,
            source: 'and',
            sourcePort: 'and-port-out',
            target: null,
            targetPort: null,
            points: [
              {
                id: 'e4916002-7182-4866-9df7-46473e7de8bc',
                type: 'point',
                x: 150,
                y: 45,
              },
              {
                id: 'd677077d-9750-4831-be02-566294c988b1',
                type: 'point',
                x: 180,
                y: 45,
              },
            ],
            labels: [],
            bifurcations: [],
            bifurcationSource: null,
            bifurcationTarget: null,
            value: null,
            bits: 1,
          },
          'button-out-link': {
            id: 'button-out-link',
            type: 'link',
            selected: false,
            source: 'button',
            sourcePort: 'c241c69b-8e1a-45be-9982-4c96a537584f',
            target: 'and',
            targetPort: 'and-port-in1',
            points: [
              {
                id: 'fbd656c6-6a36-4903-94b8-c715db34052d',
                type: 'point',
                x: 30,
                y: 75,
              },
              {
                id: 'f70cce22-3d5d-4257-9916-b602da9a901b',
                type: 'point',
                x: 60,
                y: 75,
              },
            ],
            labels: [],
            bifurcations: ['not-in-link'],
            bifurcationSource: null,
            bifurcationTarget: null,
            value: null,
            bits: 1,
          },
          'not-out-link': {
            id: 'not-out-link',
            type: 'link',
            selected: false,
            source: 'not',
            sourcePort: 'not-port-out',
            target: null,
            targetPort: null,
            points: [
              {
                id: 'ba84ed0f-78ed-43c2-93d8-cf907b91b5fd',
                type: 'point',
                x: 120,
                y: 120,
              },
              {
                id: '78a6e161-97c3-4a31-a46c-244469ac75ff',
                type: 'point',
                x: 180,
                y: 120,
              },
            ],
            labels: [],
            bifurcations: [],
            bifurcationSource: null,
            bifurcationTarget: null,
            value: null,
            bits: 1,
          },
          'not-in-link': {
            id: 'not-in-link',
            type: 'link',
            selected: false,
            source: null,
            sourcePort: null,
            target: 'not',
            targetPort: '589ba5d7-8c75-4c82-9068-a67c9b023f77',
            points: [
              {
                id: 'fada8e3b-4b46-4a24-a7ec-e3ca3bab77ab',
                type: 'point',
                x: 45,
                y: 75,
              },
              {
                id: 'f31e71e6-5d72-4f17-9af1-c23bfd257980',
                type: 'point',
                x: 45,
                y: 120,
              },
              {
                id: '2e747ee3-1c90-4e95-a40b-f221eb0710b3',
                type: 'point',
                x: 75,
                y: 120,
              },
            ],
            labels: [],
            bifurcations: [],
            bifurcationSource: 'button-out-link',
            bifurcationTarget: null,
            value: null,
            bits: 1,
          },
        },
      },
      {
        id: '9d30c1dd-e474-45b1-ad88-6b7739678ef3',
        type: 'diagram-nodes',
        isSvg: false,
        transformed: true,
        models: {
          clock: {
            id: 'clock',
            type: 'Clock',
            selected: false,
            x: 0,
            y: 0,
            ports: [
              {
                id: 'clock-port',
                type: 'Port',
                selected: false,
                x: 25,
                y: 10,
                name: 'out',
                parentNode: 'clock',
                links: ['clock-out-link'],
                input: false,
                value: null,
                bits: 1,
              },
            ],
            configurations: {
              FREQUENCY_HZ: 0.5,
              HIGH_DURATION: 1,
              LOW_DURATION: 1,
            },
          },
          and: {
            id: 'and',
            type: 'And',
            selected: false,
            x: 60,
            y: 0,
            ports: [
              {
                id: 'and-port-in0',
                type: 'Port',
                selected: false,
                x: 55,
                y: 10,
                name: 'in0',
                parentNode: 'and',
                links: ['clock-out-link'],
                input: true,
                value: null,
                bits: 1,
              },
              {
                id: 'and-port-in1',
                type: 'Port',
                selected: false,
                x: 55,
                y: 70,
                name: 'in1',
                parentNode: 'and',
                links: ['button-out-link'],
                input: true,
                value: null,
                bits: 1,
              },
              {
                id: 'and-port-out',
                type: 'Port',
                selected: false,
                x: 145,
                y: 40,
                name: 'out',
                parentNode: 'and',
                links: ['and-out-link'],
                input: false,
                value: null,
                bits: 1,
              },
            ],
            configurations: { DATA_BITS: '1', INPUT_PORTS_NUMBER: 2 },
          },
          button: {
            id: 'button',
            type: 'Button',
            selected: false,
            x: 0,
            y: 60,
            ports: [
              {
                id: 'c241c69b-8e1a-45be-9982-4c96a537584f',
                type: 'Port',
                selected: false,
                x: 25,
                y: 70,
                name: 'out',
                parentNode: 'button',
                links: ['button-out-link'],
                input: false,
                value: null,
                bits: 1,
              },
            ],
            configurations: {},
          },
          not: {
            id: 'not',
            type: 'Not',
            selected: false,
            x: 75,
            y: 105,
            ports: [
              {
                id: '589ba5d7-8c75-4c82-9068-a67c9b023f77',
                type: 'Port',
                selected: false,
                x: 70,
                y: 115,
                name: 'in',
                parentNode: 'not',
                links: ['not-in-link'],
                input: true,
                value: null,
                bits: 1,
              },
              {
                id: 'not-port-out',
                type: 'Port',
                selected: false,
                x: 115,
                y: 115,
                name: 'out',
                parentNode: 'not',
                links: ['not-out-link'],
                input: false,
                value: null,
                bits: 1,
              },
            ],
            configurations: {
              DATA_BITS: '1',
            },
          },
        },
      },
    ],
  },
};
